import type { Metadata } from "next";
import "./globals.css";
import { Montserrat, Lora } from 'next/font/google';


// import KeycloakProvider from "../context/KeycloakProvider"

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['600', '700'],
  variable: '--font-montserrat',
  display: 'swap',
});

const lora = Lora({
  subsets: ['latin'],
  weight: ['400', '500'],
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Booking store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.className} ${lora.className} h-full antialiased`}
    >
      <body className="min-h-full bg-gray-50">
        
          
            {/* <KeycloakProvider> */}
        
        {children}
        {/* </KeycloakProvider> */}
        
        </body>
    </html>
  );
}
