import type { Metadata } from "next";
import "./globals.css";
import GuestHeader from "@/components/GuestHeader";
import GuestFooter from "@/components/GuestFooter";
import { Montserrat, Lora } from 'next/font/google';
import { UserProvider } from "../context/UserContext";
import Providers from "../components/Providers";
// import KeycloakProvider from "../context/KeycloakProvider"

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['600', '700'],
  variable: '--font-montserrat',
  display: 'swap',
});

const lora = Lora({
  subsets: ['latin'],
  weight: ['400', '500'],
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Booking store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.className} ${lora.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <UserProvider>
            {/* <KeycloakProvider> */}
        <GuestHeader/>
        {children}
        <GuestFooter/>
        {/* </KeycloakProvider> */}
        </UserProvider>
        </Providers>
        </body>
    </html>
  );
}
